CREATE TABLE IF NOT EXISTS sandbox (
    id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
