version: '3.9'

services:
  aldra-db:
    container_name: aldra-db
    hostname: aldra-db
    build:
      context: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'Asia/Tokyo'
    ports:
      - '5432:5432'
    volumes:
      - aldra-db-data:/var/lib/postgresql/data
    networks:
      - aldra

volumes:
  aldra-db-data:
    name: aldra-db-data
    driver: local

networks:
  aldra:
    name: aldra
