version: '3.9'

services:
  schemaspy:
    container_name: aldra-schemaspy
    build:
      context: schemaspy
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./schemaspy/output:/output
    command: >
      java -jar /usr/local/lib/schemaspy/schemaspy.jar
         -t pgsql11
         -dp /drivers
         -o /output
         -hq
         -host aldra-db
         -port ${DB_PORT}
         -db ${DB_NAME}
         -s public
         -u ${DB_USER}
         -p ${DB_PASSWORD}
         -I "flyway_schema_history"
    networks:
      - aldra

  erd:
    container_name: aldra-erd
    image: nginx:stable
    ports:
      - '8082:80'
    volumes:
      - ./schemaspy/output:/usr/share/nginx/html:ro
    networks:
      - aldra

networks:
  aldra:
    name: aldra
