name: '[common] Check on Pull Request'

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'aldra-common/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run Spotless Check
        run: ./gradlew :common:spotlessCheck
      - name: Build aldra-api
        run: ./gradlew :common:build
